targets:
  $default:
    builders:
      riverpod_generator:
        options:
          provider_name_prefix: ""
          provider_family_name_prefix: ""
          provider_name_suffix: ""
          provider_family_name_suffix: ""
      json_serializable:
        options:
          include_if_null: false
      freezed:
        options:
          union_key: type
          union_value_case: none
