name: megaviz_chat
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.12
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  equatable: ^2.0.5
  firebase_auth: ^5.7.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.10
  firebase_storage: ^12.4.10
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^7.1.2
  flutter_hooks: ^0.21.2
  flutter_local_notifications: ^19.4.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^3.0.0
  go_router: ^15.1.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.5.1
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: any
  json_annotation: ^4.9.0
  loading_indicator: ^3.1.1
  riverpod_annotation: ^2.3.5
  mockito: ^5.4.5

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  mocktail: ^1.0.4
  remove_unused_localizations: ^1.0.1
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


