name: megaviz_chat
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  app_links: ^6.3.2
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.12
  country_code_picker: ^3.0.0
  crypto: ^3.0.6
  cupertino_icons: ^1.0.6
  device_info_plus: ^11.4.0
  dio: ^5.5.0+1
  equatable: ^2.0.5
  file_picker: ^10.1.9
  firebase_auth: ^5.7.0
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.10
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_expandable_fab: ^2.2.0
  flutter_hooks: ^0.21.2
  flutter_layout_grid: ^2.0.7
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.3.2
  flutter_quill: ^11.4.1
  flutter_rating: ^2.0.2
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^3.0.0
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  go_router: ^15.1.3
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.2
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.5.1
  http: ^1.2.1
  image: ^4.3.0
  image_cropper: ^9.1.0
  image_downloader_web: ^2.0.6
  image_picker: ^1.1.2
  intl: any
  json_annotation: ^4.9.0
  loading_indicator: ^3.1.1
  lottie: ^3.1.3
  mobile_scanner: ^7.0.1
  month_picker_dialog: ^6.2.3
  package_info_plus: ^8.1.4
  path_provider: ^2.1.4
  pdf: ^3.11.1
  permission_handler: ^12.0.0+1
  photo_view: ^0.15.0
  qr_flutter: ^4.1.0
  rich_text_controller: ^3.0.1
  riverpod_annotation: ^2.3.5
  share_plus: ^11.0.0
  shared_preferences: ^2.3.5
  sign_in_with_apple: ^7.0.1
  smooth_page_indicator: ^1.2.0+3
  sms_autofill: ^2.4.1
  socket_io_client: ^3.1.2
  syncfusion_flutter_core: ^29.2.10
  syncfusion_flutter_pdfviewer: ^29.2.10
  url_launcher: ^6.3.0
  uuid: ^4.5.1
  video_compress: ^3.1.4
  video_player: ^2.9.5
  video_thumbnail: ^0.5.6
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  mocktail: ^1.0.4
  mockito: ^5.4.5
  remove_unused_localizations: ^1.0.1
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


